class Solution:
    def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:
        """
        I am given two arrays, one contains the amount of gas I can fill at a particular station, the other contains the cost to go from the
        current station to the next one. I need to find the index at which I can travel to all stations in a circle. There is guaranteed to be a
        unique solution if one exists.

        One thing to notice is if sum(gas) < sum(cost), there is no solution (you don't have enough gas to cover the distance). If this condition
        is not true, we know a solution must exist and we can find it as follows:

        Starting from an array, begin iterating and calculating the gas surplus you have after visiting each station. If this ever goes negative
        simply start the search over from the next station. The first station found where we can get to the end of the array without a negative
        surplus is the solution. This works because we know that if we iterate, a solution must exist. Therefore, if we find a solution that
        leads to positive gas surplus, we know that it must cover the negative surplus generated by the earlier steps.

        time: O(n)
        memory: O(1)
        """
        if sum(gas) < sum(cost):
            return -1
        
        res = 0
        surplus = 0
        for i in range(len(gas)):
            # Fill gas at stations
            surplus += gas[i]
            # Travel to next station
            surplus -= cost[i]
            # Check if surplus is negative
            if surplus < 0:
                surplus = 0
                res = i+1
        return res
        
